import { Karla } from "next/font/google";
import "./globals.css";
import { FrameInit } from "@/components/FrameInit";

const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: 'no'
};

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000')
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={karla.variable}>
        {children}
        <FrameInit />
      </body>
    </html>
  );
}
